### PR TITLE
[WIP] Re-order-docs

### PR DESCRIPTION
**Pull request by JordyDutch**
Re-ordering L16 docs + adding the Luksoverse guide for nodes without validators as suggested by @fhildeb in the Supporters channel.

Added:

-  Drop-down menu for L16 docs

- Node only manual without validators

Cleaned some things up with @KEEZ-RobG

### CODE REVIEW

**Comment by JordyDutch** [comment]
Don't merge yet (Y)

**Review by JordyDutch — COMMENTED** [review]
Reverted commit[fa6ec53](https://github.com/lukso-network/docs/pull/272/commits/fa6ec53ec776063a273d84fa6cf929ee926b8480) This was pushed empty

**Comment by JordyDutch** [comment]
Check @Hugoo 👍🏼, what’s the best for now? Can you already merge this and we open a new PR to work? Or shall I close this one and copy the changed files into a new PR

**Comment by Hugoo** [comment]
@JordyDutch it is a bit hard for me to see all the changes in this PR.

You can either:

1) rebase your PR on main
2) merge main in your PR
3) create a new branch from main and cherry pick commits from this branch
4) create a new branch and "do it manually"

**Pull request closed without merging**
