### PR TITLE
Update schemas.md

### PR DESCRIPTION
**Pull request by EngrGord**

### CODE REVIEW

**Comment by Hugoo** [comment]
thanks - we need to update it in the erc725 js repo too:

https://github.com/ERC725Alliance/erc725.js/tree/develop/docs

**Comment by EngrGord** [comment]
Ok, I'll do that now.

**Comment by EngrGord** [comment]
Ok, Will do that now.

**Comment by Hugoo** [comment]
I made the change here: https://github.com/ERC725Alliance/erc725.js/pull/224

**Pull request closed without merging**
