### PR TITLE
Update LSP16UniversalFactory.md

### PR DESCRIPTION
**Pull request by 0xbasar**
Hi,

I found some errors and suggest changes accordingly:

1. Duplicate Sentence: See generateSalt function for more details. See generateSalt function for more details.

2. Original: Proxy deployed & initialized. Salt, providedSalt, used.
Suggested Change: Proxy deployed & initialized. Salt, providedSalt, are used.

3. Original: Emitted whenever a contract is created.
Suggested Change: Emits whenever a contract is created.

### CODE REVIEW

**Comment by fhildeb** [comment]
Thank you for your feedback!- an eye for details 💫

I let the build workflow run. We can merge the PR as soon as it's completed.

**Review by skimaharvey — APPROVED** [review]
🙏

**Comment by Hugoo** [comment]
@fhildeb - we made changes in the Cloudflare API token for security reasons. I'll fix it by eod.

**Review by YamenMerhi — CHANGES_REQUESTED** [review]
Thanks for the contribution!
This document is autogenerated from the natspec comments of the `LSP16UniversalFactory.sol` contract in the [lsp-smart-contract](https://github.com/lukso-network/lsp-smart-contracts) repo. 

We might re-deploy the contract and finalize LSP16 soon, do you want to open a PR with the same change in the other repo ? @0xbasar 

The changes looks good, I would personally keep emitted instead of emits and for the second suggested change, can you apply it for all occurrence?

**Comment by fhildeb** [comment]
@YamenMerhi Right. I've just remembered that it was an externally loaded page. I've created a PR and applied your suggestions: <https://github.com/lukso-network/lsp-smart-contracts/pull/838>

Did not have permissions on [`lsp-smart-contracts`](https://github.com/lukso-network/lsp-smart-contracts/) and couldn't create a branch. Feel free to adjust the wording any further.

**Comment by 0xbasar** [comment]
Sorry but I didn't understand what should I do? Could you please explain it more?

**Comment by fhildeb** [comment]
@0xbasar, there is nothing to do anymore from your side.

This page of the docs is loaded from an external repository (the one linked above) and automatically generated from the code documentary. So, we won't be able to change it here because the change will be overwritten whenever we reload the content.

I ported your PR over to the correct repository and applied @YamenMerhi's suggestions:
https://github.com/lukso-network/lsp-smart-contracts/pull/838

I will close this PR so we don't have a duplicate. Feel free to put new comments on `lsp-smart-contracts`

**Pull request closed without merging**
