### PR TITLE
chore: updated typos to improve readability

### PR DESCRIPTION
**Pull request by clarencepenz**
This PR fixes typos found in the documentation

### CODE REVIEW

**Review by fhildeb — COMMENTED** [review]
Thanks for all those grammar improvements! ☺️🙏🏻

We are pulling all the files within `contracts/contracts/` from the [`@lsp-smart-contracts`](https://github.com/lukso-network/lsp-smart-contracts/tree/develop/contracts) repository. 

Could you open this PR there, please? We can then pull in the latest changes.
You can read more in the [CONTRIBUTING.md](https://github.com/lukso-network/lsp-smart-contracts/blob/develop/CONTRIBUTING.md) of the LSP repo.

**Comment by clarencepenz** [comment]
Oh! I didn’t realize. I’ll get right on it. @fhildeb

**Comment by Hugoo** [comment]
@CJ42 @b00ste fyi -> this PR is fixing lot of typos in the contracts repo.

**Comment by Hugoo** [comment]
Thanks @clarencepenz for the PR! 🫡

**Comment by clarencepenz** [comment]
My pleasure @Hugoo

**Comment by fhildeb** [comment]
It's great to see this PR on the other repo 💪🏻

https://github.com/lukso-network/lsp-smart-contracts/pull/887 

I will close this one for duplication. Thanks again for your contribution ❤️

**Pull request closed without merging**
