### PR TITLE
Pre-release L16 FAQ

### PR DESCRIPTION
**Pull request by JordyDutch**
FAQ questions are answered by Lenny and Nando. Fabian also checked it.

### CODE REVIEW

**Review by lykhonis — APPROVED** [review]
LGTM

**Comment by fhildeb** [comment]
I would suggest to edit/input the dynamic link to this FAQ at

https://docs.lukso.tech/networks/l16-testnet#faq

**Comment by JordyDutch** [comment]
> I would suggest to edit/input the dynamic link to this FAQ at
> 
> https://docs.lukso.tech/networks/l16-testnet#faq

Yes, Was just doing that haha. Thanks!

**Comment by Hugoo** [comment]
Thanks @JordyDutch !

**Pull request merged**
