### PR TITLE
Update Multi Provider Guide

### PR DESCRIPTION
**Pull request by fhildeb**
## PR Features

Changes the previous Web3 Onboard Page to a general Multi Provider Connection Guide, featuring both- Web3Modal from Wallet Connect and Web3 Onboard from Blocknative.

## Screenshots

img1
img2

### CODE REVIEW

**Comment by rowkee** [comment]
I might be misunderstanding here, but I thought we had three ways (and therefore there should be 3 tabs) for 

1. Vanilla EIP6963
2. Web3 Modal 
3. Web3 Onboard

**Comment by fhildeb** [comment]
Vanilla EIP-6963 is already covered on the Connection page (with a link to our example repo)

This page will only show how to integrate external wallet tools. @rowkee

**Comment by rowkee** [comment]
Not necessarily,  as long as "multi provider connection" is the term devs would search for or is the common term used so they'd recognise what it was if they saw it then all good.

**Review by CJ42 — APPROVED** [review]
I am approving to speed up the merging, as @frozeman approved it already

**Pull request merged**
