### PR TITLE
Re-organise sidebar of Learn section

### PR DESCRIPTION
**Pull request by CJ42**
image

### CODE REVIEW

**Review by Hugoo — CHANGES_REQUESTED** [review]
Do not forget redirects from old page to new page

**Comment by rowkee** [comment]
Are the `-` just strings? and supposed to be an indent? If so, should we not keep them as drop downs?

**Comment by CJ42** [comment]
> Are the `-` just strings? and supposed to be an indent? If so, should we not keep them as drop downs?

I could try, but I think it really create a big nesting. Let me check

**Comment by CJ42** [comment]
PR moved to draft as several things are broken. Including code syntax highlighting

**Comment by CJ42** [comment]
Reverted the change for renaming from `Learn` to `Tutorial`, as this is a big change for the SEO, etc... and we should discuss this together first in team.

@rowkee for this:

> Are the `-` just strings? and supposed to be an indent? If so, should we not keep them as drop downs?

Agree I remove the "bullet" list `-` and moved the re-org of the internal items with dropdowns in #1004 🫡

**Review by rowkee — APPROVED** [review]
LGTM

**Pull request merged**
